// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThAmCo.Catering.Models;

namespace ThAmCo.Catering.Migrations
{
    [DbContext(typeof(CateringContext))]
    [Migration("20211113233005_initialMigration")]
    partial class initialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ThAmCo.Catering.Models.FoodItem", b =>
                {
                    b.Property<int>("FoodItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("UnitPrice")
                        .HasColumnType("real");

                    b.HasKey("FoodItemID");

                    b.ToTable("FoodItems");

                    b.HasData(
                        new
                        {
                            FoodItemID = 1,
                            Description = "Shepherd’s Pie",
                            UnitPrice = 3.5f
                        },
                        new
                        {
                            FoodItemID = 2,
                            Description = "Beef Wellington",
                            UnitPrice = 5f
                        },
                        new
                        {
                            FoodItemID = 3,
                            Description = "Fish and Chips",
                            UnitPrice = 3.75f
                        },
                        new
                        {
                            FoodItemID = 4,
                            Description = "Chicken Tikka Masala",
                            UnitPrice = 2.5f
                        },
                        new
                        {
                            FoodItemID = 5,
                            Description = "Steak and Kidney pie",
                            UnitPrice = 3.75f
                        },
                        new
                        {
                            FoodItemID = 6,
                            Description = "Eton Mess",
                            UnitPrice = 5.5f
                        },
                        new
                        {
                            FoodItemID = 7,
                            Description = "Cornish pasty",
                            UnitPrice = 3.25f
                        },
                        new
                        {
                            FoodItemID = 8,
                            Description = "Bangers and Mash",
                            UnitPrice = 2.95f
                        },
                        new
                        {
                            FoodItemID = 9,
                            Description = "Toad in the hole",
                            UnitPrice = 2.6f
                        },
                        new
                        {
                            FoodItemID = 10,
                            Description = "Rib Eye Steak",
                            UnitPrice = 4.9f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
